server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/products
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/products
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus